---

- name: Setup servers 
  become: yes
  gather_facts: yes
  become_method: sudo
  any_errors_fatal: true
  hosts: all
  vars_files:
    - vars/.secret.yml
    - vars/setup.yml
    
  pre_tasks:
    - name: Include OS-specific variables
      include_vars: "vars/{{ ansible_os_family }}.yml"

  roles:
    - role: ping
    - role: os_type
  
  