---
# default user
ansible_user: user
ansible_password: ""

# create users list
create_users:
  - {username: dbadmin,  user_password: "dbadmin",  create_home: true, groups: sudo, sudoers: true, nopasswd: true ,commands: "ALL"}
  - {username: sysadmin, user_password: "sysadmin", create_home: true, groups: sudo, sudoers: true, nopasswd: true ,commands: "ALL"}
  - {username: tester, user_password: "123", create_home: false, groups: "", sudoers: false, nopasswd: false ,commands: ""}


# ssh-keys for users
ssh_keys_users:
  - {username: dbadmin, key: ""}
  - {username: sysadmin, key: ""}

